language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

os:
  - linux

branches:
  only:
    - staging
    - trying
    - master
    - travis

before_script: echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
script:
  - composer install
  - ./vendor/bin/atoum
